name: 'Deploy Build folder to GitHub Pages'
description: 'This action will handle deployment and keeps track of deployment changes.'
author: 'Saw-mon & Natalie <samangharib50233@gmail.com>'
runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    icon: 'git-commit'
    color: 'blue'